"""
setup_turso.py — Interactive setup for the Turso / libSQL community DB.

Guides the user through:
  1. Checking prerequisites (python version, network)
  2. Asking for the Turso URL and auth token (interactive, never logged)
  3. Testing the connection (cheap SELECT 1)
  4. Applying the cloud schema (database/cloud_schema.sql) — idempotent
  5. Saving credentials to .env (chmod 600 on POSIX, gitignored)
  6. Verifying the schema by listing tables
  7. Printing next steps

Usage:
    python scripts/setup_turso.py
    python scripts/setup_turso.py --url libsql://xxx --token eyJ... (non-interactive)
    python scripts/setup_turso.py --verify   # just test existing .env

No data is sent anywhere except the Turso URL the user provides.
The .env file is created with restrictive permissions on POSIX systems.
"""

import argparse
import os
import sys
import stat
import time
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
ENV_FILE = PROJECT_ROOT / ".env"
ENV_EXAMPLE = PROJECT_ROOT / ".env.example"
SCHEMA_FILE = PROJECT_ROOT / "database" / "cloud_schema.sql"
GITIGNORE = PROJECT_ROOT / ".gitignore"


def _hr() -> None:
    print("─" * 60)


def _step(msg: str) -> None:
    print(f"\n→ {msg}")


def _ok(msg: str) -> None:
    print(f"  ✓ {msg}")


def _warn(msg: str) -> None:
    print(f"  ⚠ {msg}")


def _err(msg: str) -> None:
    print(f"  ✗ {msg}")


def _load_env() -> dict:
    """Load .env file into a dict (simple KEY=VALUE parser, no expansion)."""
    env = {}
    if ENV_FILE.exists():
        for line in ENV_FILE.read_text(encoding="utf-8").splitlines():
            line = line.strip()
            if not line or line.startswith("#") or "=" not in line:
                continue
            k, v = line.split("=", 1)
            env[k.strip()] = v.strip()
    return env


def _save_env(env: dict) -> None:
    """Write .env file. On POSIX, chmod 600 (only owner can read)."""
    lines = [
        "# LMU Pit Strategist — Turso / libSQL credentials",
        "# Generated by scripts/setup_turus.py — do NOT commit this file",
        "",
    ]
    for k, v in env.items():
        # Quote values that contain spaces or special chars
        if any(c in v for c in " #\"'"):
            v = '"' + v.replace('"', '\\"') + '"'
        lines.append(f"{k}={v}")
    ENV_FILE.write_text("\n".join(lines) + "\n", encoding="utf-8")
    # Restrictive permissions (POSIX only)
    try:
        os.chmod(ENV_FILE, stat.S_IRUSR | stat.S_IWUSR)
        _ok(f"Wrote {ENV_FILE} (chmod 600)")
    except (AttributeError, OSError):
        # Windows: chmod has limited effect
        _ok(f"Wrote {ENV_FILE}")


def _ensure_gitignore() -> None:
    """Ensure .env is in .gitignore so it's never committed."""
    if not GITIGNORE.exists():
        return
    content = GITIGNORE.read_text(encoding="utf-8")
    if ".env" not in content:
        with GITIGNORE.open("a", encoding="utf-8") as f:
            f.write("\n# Local credentials (created by setup_turus.py)\n")
            f.write(".env\n")
        _ok("Added .env to .gitignore")
    else:
        _ok(".env already in .gitignore")


def _install_libsql_client() -> bool:
    """Install libsql-client if missing. Returns True if installed/present."""
    try:
        import libsql_client  # noqa
        return True
    except ImportError:
        _step("libsql-client not installed, attempting pip install...")
        import subprocess
        result = subprocess.run(
            [sys.executable, "-m", "pip", "install", "libsql-client"],
            capture_output=True, text=True,
        )
        if result.returncode == 0:
            _ok("libsql-client installed")
            return True
        _err("pip install failed:")
        print(result.stderr[-500:])
        return False


def _test_connection(url: str, token: str) -> bool:
    """Run a cheap query to verify connectivity."""
    try:
        import libsql_client
    except ImportError:
        _err("libsql-client not available — cannot test connection")
        return False
    try:
        client = libsql_client.create_client(url=url, auth_token=token)
        result = client.execute("SELECT 1 AS ok")
        rows = list(result)
        if rows and rows[0][0] == 1:
            _ok("Connection successful")
            return True
        _err("Unexpected response from server")
        return False
    except Exception as e:
        _err(f"Connection failed: {e}")
        return False


def _apply_schema(url: str, token: str) -> bool:
    """Run database/cloud_schema.sql on the remote. Idempotent (CREATE IF NOT EXISTS)."""
    if not SCHEMA_FILE.exists():
        _err(f"Schema file not found: {SCHEMA_FILE}")
        return False
    sql = SCHEMA_FILE.read_text(encoding="utf-8")
    statements = [s.strip() for s in sql.split(";") if s.strip()]

    try:
        import libsql_client
        client = libsql_client.create_client(url=url, auth_token=token)
        # libsql_client doesn't support multi-statement execute in older
        # versions, so we run each statement individually. CREATE TABLE
        # IF NOT EXISTS makes this safe to re-run.
        for i, stmt in enumerate(statements, 1):
            try:
                client.execute(stmt)
            except Exception as e:
                # Some statements may be CREATE INDEX on a non-existent
                # table if the table creation was skipped; skip and warn
                if "no such table" in str(e).lower():
                    _warn(f"Skipped statement {i} (table missing)")
                    continue
                raise
        _ok(f"Applied {len(statements)} schema statements (idempotent)")
        return True
    except Exception as e:
        _err(f"Schema application failed: {e}")
        return False


def _verify_schema(url: str, token: str) -> bool:
    """List tables to confirm the schema landed."""
    try:
        import libsql_client
        client = libsql_client.create_client(url=url, auth_token=token)
        result = client.execute(
            "SELECT name FROM sqlite_master WHERE type='table' ORDER BY name"
        )
        tables = [r[0] for r in result.rows]
        expected = {"users", "sessions", "stints", "laps", "pit_stops", "community_meta"}
        present = set(tables)
        missing = expected - present
        _ok(f"Remote tables: {', '.join(tables)}")
        if missing:
            _warn(f"Missing tables: {', '.join(missing)}")
            return False
        _ok("All expected tables present ✓")
        return True
    except Exception as e:
        _err(f"Schema verification failed: {e}")
        return False


def _write_env_example() -> None:
    """Create .env.example template if it doesn't exist."""
    if ENV_EXAMPLE.exists():
        return
    ENV_EXAMPLE.write_text(
        "# Copy this file to .env and fill in your Turso credentials.\n"
        "# .env is in .gitignore — never commit it.\n"
        "#\n"
        "# Get these values from https://turso.tech after creating a database:\n"
        "#   turso db create lmu-pit-strategist\n"
        "#   turso db tokens create lmu-pit-strategist\n"
        "#\n"
        "TURSO_URL=libsql://lmu-pit-strategist-yourname.turso.io\n"
        "TURSO_TOKEN=\n",
        encoding="utf-8",
    )
    _ok(f"Created {ENV_EXAMPLE}")


def _prompt(question: str, default: str = "") -> str:
    suffix = f" [{default}]" if default else ""
    val = input(f"  {question}{suffix}: ").strip()
    if not val and default:
        return default
    return val


def cmd_setup_interactive(args) -> int:
    """Full interactive setup flow."""
    # If --url is passed but --token is missing/empty, fail early
    # (don't go into interactive mode)
    if args.url and not args.token:
        print("  ✗ Token is required when --url is provided", file=sys.stderr)
        return 1

    # Treat empty string from --token "" as "not provided"
    non_interactive = bool(args.url) and bool(args.token)
    if non_interactive:
        print("═" * 60)
        print("  LMU Pit Strategist — Turso setup (non-interactive)")
        print("═" * 60)
    else:
        _hr()
        print("  LMU Pit Strategist — Turso setup")
        _hr()
        print("This will:")
        print("  1. Install libsql-client (if needed)")
        print("  2. Ask for your Turso URL and auth token")
        print("  3. Test the connection")
        print("  4. Apply the cloud schema (idempotent)")
        print("  5. Save credentials to .env (chmod 600, gitignored)")
        print()
        print("Your credentials will be saved LOCALLY only (in .env).")
        print("They are NEVER sent to anyone except the Turso URL you provide.")
        _hr()
        try:
            input("Press Enter to continue (Ctrl+C to abort)...")
        except EOFError:
            print("Aborted: no interactive input available.")
            return 1

    # 1. libsql-client
    if not _install_libsql_client():
        return 1

    # 2. Ask for credentials
    _step("Turso credentials")
    if args.url:
        url = args.url
    else:
        try:
            url = _prompt(
                "Turso URL (e.g. libsql://lmu-pit-strategist-yourname.turso.io)"
            )
        except EOFError:
            _err("No input available — pass --url and --token for non-interactive mode")
            return 1
    if not url.startswith("libsql://") and not url.startswith("https://"):
        _err(f"Invalid URL format: {url}")
        _err("Must start with libsql:// or https://")
        return 1

    if args.token:
        token = args.token
    else:
        try:
            token = _prompt("Turso auth token (from `turso db tokens create`)")
        except EOFError:
            _err("No input available — pass --url and --token for non-interactive mode")
            return 1

    if not token:
        _err("Token is required")
        return 1

    # 3. Test connection
    _step("Testing connection...")
    if not _test_connection(url, token):
        return 1

    # 4. Apply schema
    _step("Applying cloud schema...")
    if not _apply_schema(url, token):
        return 1

    # 5. Save
    _step("Saving credentials...")
    _write_env_example()
    _save_env({"TURSO_URL": url, "TURSO_TOKEN": token})
    _ensure_gitignore()

    # 6. Verify
    _step("Verifying schema...")
    if not _verify_schema(url, token):
        _warn("Schema verification failed — you may need to re-run later")

    _hr()
    print("  ✓ Setup complete!")
    _hr()
    print()
    print("Next steps:")
    print("  1. Start the web UI:  python run_app.py")
    print("  2. Open http://127.0.0.1:8000 → opt in to the community DB")
    print("  3. Or use the overlay:  python run_overlay_live.py --modular")
    print("  4. Click ⚙ → '☁️ Attiva community DB'")
    print()
    print("Your .env is ready. To re-run setup: python scripts/setup_turso.py")
    print("To verify: python scripts/setup_turso.py --verify")
    print()
    return 0


def cmd_verify(args) -> int:
    """Verify existing .env setup."""
    env = _load_env()
    if "TURSO_URL" not in env or "TURSO_TOKEN" not in env:
        _err("No Turso credentials in .env. Run setup first.")
        return 1
    _step(f"Found TURSO_URL={env['TURSO_URL'][:30]}...")
    if not _test_connection(env["TURSO_URL"], env["TURSO_TOKEN"]):
        return 1
    return _verify_schema(env["TURSO_URL"], env["TURSO_TOKEN"])


def main():
    parser = argparse.ArgumentParser(
        description="LMU Pit Strategist — Turso setup wizard",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument("--url", help="Turso URL (skip interactive prompt)")
    parser.add_argument("--token", help="Turso auth token (skip interactive prompt)")
    parser.add_argument(
        "--verify", action="store_true",
        help="Just verify an existing .env setup (no changes)",
    )
    args = parser.parse_args()

    if args.verify:
        return cmd_verify(args)
    return cmd_setup_interactive(args)


if __name__ == "__main__":
    sys.exit(main())
